### ISSUE TITLE
Hook appears to parse tokens/tokenfiles beginning with a dash as options

### ISSUE THREAD

**Issue by pinkgothic** [eferdman/dnspython-hook#18]
I've been trying to get this hook to work for quite a while now, chiefly struggling with a flaky DNS setup. That said, every once in a while, the hook would throw the error `usage: dehydrated-hook-ddns-tsig.py deploy_challenge [-h] [...]` when run within dehydrated. After some debugging, I finally got a hook call echoed in dehydrated that triggered the issue.

The call was something like this:

`/root/dehydrated/hooks/ddns-tsig/dehydrated-hook-ddns-tsig.py deploy_challenge foo.example.com -3z_kv-zTZ7RXgUaPA74K1fb8UgKghpqgK-Zizqyors J1JChd3ID2wbmLhgswZCC-YZLHaXIc3Af2W7PyizFnY`

(Tokenfile and token exact same ones that the error was observed with.)

The full problem reported by the hook was this:

`dehydrated-hook-ddns-tsig.py deploy_challenge: error: too few arguments`

...or this (when multiple tokens were deployed through the hook simultaneously):

`dehydrated-hook-ddns-tsig.py deploy_challenge: error: unrecognized arguments: -3z_kv-zTZ7RXgUaPA74K1fb8UgKghpqgK-Zizqyors`

Notice the dash (`-`) in the beginning of the token.

~~I am currently terrible at Python so I don't know if I can offer up a pull request to fix this, but I'm going to try dealing with it in my own installation; if the solution's even slightly worthwhile, you'll definitely get a pull request. I just don't trust myself to get it right, much less be quick about it, so I wanted to make a ticket first.~~ I ended up injecting `--` into `sys.argv`. This is very messy, but I was unable to get solutions involving `nargs=argparse.PARSE`, `nargs=argparse.REMAINDER`, or `parse_known_args()` to work. Due to my extreme Python-newbishness, I can't guarantee those are dead ends. Either way, you definitely don't want my solution as a pull request, it is not even slightly robust. >_>

**Comment by umlaeute** [comment]
this issue should be closed as it was addressed with PR #19
