### ISSUE TITLE
hook fails in case of IPv6 only host

### ISSUE THREAD

**Issue by Farom** [eferdman/dnspython-hook#23]
In case of having an IPv6-only Server, the hook always runs into 30s timeout because the verifying uses IPv4 addresses for reaching.

**Comment by umlaeute** [comment]
could you provide detailed steps to reproduce the issue?

**Comment by umlaeute** [comment]
also, i'm not sure i understand what you mean with "the verifying uses IPv4 addresses", and how you come to that conclusion.

**Comment by Farom** [comment]
look at  line 156 of dehydrated-hook-ddns-tsig.py

 ```
for rdata in dns.resolver.query('.'.join(name_list[i:]),
                                                       'NS')]:
```
dns.resolfver.query only requests A records. It is the default in dnspython.
Now you try to verify the deployed challenge from an IPv4-DNS-server you cannot reach cause your host is IPv6 only.

This should fail immediately, but dnspython does not give you a reasonable error back after a 30s timeout. (maybe we could set a 'lifetime' for the resolver ... but this is another task)

I forked and fixed it for me. I'll send you a pull request in a moment.

**Comment by Farom** [comment]
Here is the code from /usr/lib/python2.7/dist-packages/dns/resolver.py. I hope you'll see the problem.

```
def query(self, qname, rdtype=dns.rdatatype.A, rdclass=dns.rdataclass.IN,
          tcp=False, source=None, raise_on_no_answer=True, source_port=0):

```

**Comment by Farom** [comment]
my patch was pulled.
