### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by Farom** [eferdman/dnspython-hook#26]
I need dehydrated-hook-ddns-tsig to working IPv6-only in debian, but the Maintainer only updates the package if you make a Release first.
(https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908024)
so please make a new release.

**Comment by umlaeute** [comment]
this can be closed. thanks @eferdman

**Comment by Farom** [comment]
Thanks a lot.
