### ISSUE TITLE
fails to add TXT records for subdomains

### ISSUE THREAD

**Issue by umlaeute** [eferdman/dnspython-hook#4]
Considering i have a zone-file `example.com`, that contains *A* records for both `example.com` itself and for `foo.example.com`.

Then, *dnshook-python* is able to create a *TXT* record for  `_acme-challenge.example.com`, but fails to create a record for  `_acme-challenge.foo.example.com`.

bind9 gives me the following error:
> Dec 13 18:52:59 bind9 named[1234]: update: info: client 192.0.2.32#40201/key secret-key: updating zone 'example.com/IN': update failed: not authoritative for update zone (NOTAUTH)

The issue seems to be that *dnshook-python* requests to add a *TXT* entry for `_acme-challenge` in the `foo.example.com` zone, which does not exist on the server.
instead it should create an entry for  `_acme-challenge.foo` in the `example.com` zone.

**Comment by umlaeute** [comment]
btw, i'm preparing a fix for this.

**Comment by eferdman** [comment]
Great! I was confused about this. I posted about it in the dnspython users mailing list a while back (no reply :/):
https://groups.google.com/forum/#!topic/dnspython-users/miXNcGSquCU

So I guess dnspython looks for the specific zone file and only adds TXTs on top of the main domain, not on top of subdomains. So then I guess it's necessary to know the name of the zone file. I know that with nsupdate this is not a problem so I was wondering why dnspython was saying 'not authoritative'.

**Comment by umlaeute** [comment]
actually i'm pretty sure that I had the same problem with `nsupdate` (at least this is how i guessed the actual problem).

Something like this would work

~~~nsupdate
zone example.com
update add _acme-challenge.foo 300 TXT "secret"
send
~~~

but this would not:
~~~nsupdate
zone foo.example.com
update add _acme-challenge 300 TXT "secret"
send
~~~

(the above snippets are sketched without any tests; but you get the idea).
