### ISSUE TITLE
renaming project to something more meaningful?

### ISSUE THREAD

**Issue by umlaeute** [eferdman/dnspython-hook#8]
i'm currently in the process of including your script in Debian, and I would like to have the package a meaningful name that matches your project :-)

so could you please consider renaming the project to something more meaningful?
the only info that the current name `dnspython-hook` bears is that it is an addon (*hook*) to some unknown application and that it uses a certain library to achieve its goal - whatever that goal is.

here are some suggestions (by @dpocock)
- dehydrated-hook-ddns
- **dehydrated-hook-ddns-tsig**
- dehydrated-hook-ddns-rfc2136
- dehydrated-hook-nsupdate (although it doesn't use the nsupdate binary)

(i've taken the liberty to highlight my favourite)

**Comment by umlaeute** [comment]
ah btw, github keeps old links around, so even if you do rename the project, it will still be available under https://github.com/eferdman/dnspython-hook

E.g. confirm the `dehydrated`-project itself, which used to be available under https://github.com/lukas2511/letsencrypt.sh (and it still is!)

**Comment by dpocock** [comment]
@umlaeute thanks for following up on this.

@lukas2511 how would you feel about a team-managed organization on Github to keep all the different hook scripts for dehydrated?  Then we could push this project into a repository under the organization URL.

**Comment by dpocock** [comment]
@eferdman thanks for renaming the repository Liz

@umlaeute do you think any files need to be renamed too and/or anything in the docs?  Maybe you could submit a pull request for that and then Liz can accept it?

**Comment by umlaeute** [comment]
repo and script have been renamed; closing
